import localFont from "next/font/local";
import "./globals.css";
import styles from "../styles/Navbar.module.css"
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "MovieTalks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <header className={styles.navbarBox}>
        <Link href="/">        <p className={styles.navbarLogo}>
        Movie<span style={{ color: "white" }}>Talks</span>
      </p></Link>
      
          <nav className="flex gap-8">

            
            <Link className={styles.navbarButton} href="/signin">Login</Link>
            <Link className={styles.navbarButton} href="/signup">Create Account</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
//this navigation bar will be used before user signin or signup